# Posttest_4
Nama  : Hendi
NIM   : 2009106009
Kelas : Praktikum Kecerdasn Buatan A1 2020

## Import Library

In [71]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import MinMaxScaler
from sklearn.preprocessing import StandardScaler
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import OneHotEncoder

In [72]:
df = pd.read_csv("income_evaluation.csv")
df.head()

age          workclass   fnlwgt   education   education-num  \
0   39          State-gov    77516   Bachelors              13   
1   50   Self-emp-not-inc    83311   Bachelors              13   
2   38            Private   215646     HS-grad               9   
3   53            Private   234721        11th               7   
4   28            Private   338409   Bachelors              13   

        marital-status          occupation    relationship    race      sex  \
0        Never-married        Adm-clerical   Not-in-family   White     Male   
1   Married-civ-spouse     Exec-managerial         Husband   White     Male   
2             Divorced   Handlers-cleaners   Not-in-family   White     Male   
3   Married-civ-spouse   Handlers-cleaners         Husband   Black     Male   
4   Married-civ-spouse      Prof-specialty            Wife   Black   Female   

    capital-gain   capital-loss   hours-per-week  native-country  income  
0           2174              0               40   United-States   <=50K  
1              0              0               13   United-States   <=50K  
2              0              0               40   United-States   <=50K  
3              0              0               40   United-States   <=50K  
4              0              0               40            Cuba   <=50K

## Data Split

In [73]:
Y = df.iloc[:,-1]
X = df.iloc[:,:-1]

X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.3)

In [74]:
print("X_train : ", X_train.shape)
print("X_train : ", X_test.shape)
print("Y_train : ", Y_train.shape)
print("Y_test : ", Y_test.shape)

X_train :  (22792, 14)
X_train :  (9769, 14)
Y_train :  (22792,)
Y_test :  (9769,)


## Normalisasi Data

In [75]:
df.dtypes

age                 int64
 workclass         object
 fnlwgt             int64
 education         object
 education-num      int64
 marital-status    object
 occupation        object
 relationship      object
 race              object
 sex               object
 capital-gain       int64
 capital-loss       int64
 hours-per-week     int64
 native-country    object
 income            object
dtype: object

In [76]:
df2 = df[['age', ' fnlwgt', ' education-num', ' capital-gain', ' capital-loss', ' hours-per-week']]
df2.head()

age   fnlwgt   education-num   capital-gain   capital-loss   hours-per-week
0   39    77516              13           2174              0               40
1   50    83311              13              0              0               13
2   38   215646               9              0              0               40
3   53   234721               7              0              0               40
4   28   338409              13              0              0               40

In [77]:
ss = MinMaxScaler()

## Standarisasi Data

In [78]:
Scaled_data = ss.fit_transform(df2)

In [79]:
print("Data Sebelum scalling : ")
print(df2)
print("Nilai standar deviasi: \n", np.std(df2))

Data Sebelum scalling : 
       age   fnlwgt   education-num   capital-gain   capital-loss  \
0       39    77516              13           2174              0   
1       50    83311              13              0              0   
2       38   215646               9              0              0   
3       53   234721               7              0              0   
4       28   338409              13              0              0   
...    ...      ...             ...            ...            ...   
32556   27   257302              12              0              0   
32557   40   154374               9              0              0   
32558   58   151910               9              0              0   
32559   22   201490               9              0              0   
32560   52   287927               9          15024              0   

        hours-per-week  
0                   40  
1                   13  
2                   40  
3                   40  
4                   4

In [80]:
print("Data sesudah scalling : ")
print(Scaled_data)
print("Nilai standar deviasi: ", np.std(Scaled_data))

Data sesudah scalling : 
[[0.30136986 0.0443019  0.8        0.02174022 0.         0.39795918]
 [0.45205479 0.0482376  0.8        0.         0.         0.12244898]
 [0.28767123 0.13811345 0.53333333 0.         0.         0.39795918]
 ...
 [0.56164384 0.09482688 0.53333333 0.         0.         0.39795918]
 [0.06849315 0.12849934 0.53333333 0.         0.         0.19387755]
 [0.47945205 0.18720338 0.53333333 0.1502415  0.         0.39795918]]
Nilai standar deviasi:  0.2508287602095078


In [81]:
df3 = df[['age', ' fnlwgt', ' education-num', ' capital-gain', ' capital-loss', ' hours-per-week'  ]]
df3.head()

age   fnlwgt   education-num   capital-gain   capital-loss   hours-per-week
0   39    77516              13           2174              0               40
1   50    83311              13              0              0               13
2   38   215646               9              0              0               40
3   53   234721               7              0              0               40
4   28   338409              13              0              0               40

In [82]:
ss = StandardScaler()
Scaled_data = ss.fit_transform(df3)

In [83]:
print("Data Sebelum scalling : ")
print(df3)
print("Nilai standar deviasi: \n", np.std(df3))

Data Sebelum scalling : 
       age   fnlwgt   education-num   capital-gain   capital-loss  \
0       39    77516              13           2174              0   
1       50    83311              13              0              0   
2       38   215646               9              0              0   
3       53   234721               7              0              0   
4       28   338409              13              0              0   
...    ...      ...             ...            ...            ...   
32556   27   257302              12              0              0   
32557   40   154374               9              0              0   
32558   58   151910               9              0              0   
32559   22   201490               9              0              0   
32560   52   287927               9          15024              0   

        hours-per-week  
0                   40  
1                   13  
2                   40  
3                   40  
4                   4

In [84]:
print("Data sesudah scalling : ")
print(Scaled_data)
print("Nilai standar deviasi: ", np.std(Scaled_data))

Data sesudah scalling : 
[[ 0.03067056 -1.06361075  1.13473876  0.1484529  -0.21665953 -0.03542945]
 [ 0.83710898 -1.008707    1.13473876 -0.14592048 -0.21665953 -2.22215312]
 [-0.04264203  0.2450785  -0.42005962 -0.14592048 -0.21665953 -0.03542945]
 ...
 [ 1.42360965 -0.35877741 -0.42005962 -0.14592048 -0.21665953 -0.03542945]
 [-1.21564337  0.11095988 -0.42005962 -0.14592048 -0.21665953 -1.65522476]
 [ 0.98373415  0.92989258 -0.42005962  1.88842434 -0.21665953 -0.03542945]]
Nilai standar deviasi:  1.0


## Data Cleaning

In [85]:
df.isna().sum()

age                0
 workclass         0
 fnlwgt            0
 education         0
 education-num     0
 marital-status    0
 occupation        0
 relationship      0
 race              0
 sex               0
 capital-gain      0
 capital-loss      0
 hours-per-week    0
 native-country    0
 income            0
dtype: int64

In [86]:
df.dtypes

age                 int64
 workclass         object
 fnlwgt             int64
 education         object
 education-num      int64
 marital-status    object
 occupation        object
 relationship      object
 race              object
 sex               object
 capital-gain       int64
 capital-loss       int64
 hours-per-week     int64
 native-country    object
 income            object
dtype: object

In [87]:
imputer = SimpleImputer(strategy='most_frequent' )

df["age"] = imputer.fit_transform(df[["age"]])
df["fnlwgt"] = imputer.fit_transform(df[[" fnlwgt"]])
df[" education-num"] = imputer.fit_transform(df[[" education-num"]])
df[" capital-gain"] = imputer.fit_transform(df[[" capital-gain"]])
df[" capital-loss"] = imputer.fit_transform(df[[" capital-loss"]])
df[" hours-per-week"] = imputer.fit_transform(df[[" hours-per-week"]])

In [88]:
df.isna().sum()

age                0
 workclass         0
 fnlwgt            0
 education         0
 education-num     0
 marital-status    0
 occupation        0
 relationship      0
 race              0
 sex               0
 capital-gain      0
 capital-loss      0
 hours-per-week    0
 native-country    0
 income            0
fnlwgt             0
dtype: int64

## Data Cleaning (Duplikat)

In [89]:
print("Data Duplikat: ")
df[df.duplicated()]

Data Duplikat: 


age          workclass   fnlwgt      education   education-num  \
4881    25            Private   308144      Bachelors              13   
5104    90            Private    52386   Some-college              10   
9171    21            Private   250051   Some-college              10   
11631   20            Private   107658   Some-college              10   
13084   25            Private   195994        1st-4th               2   
15059   21            Private   243368      Preschool               1   
17040   46            Private   173243        HS-grad               9   
18555   30            Private   144593        HS-grad               9   
18698   19            Private    97261        HS-grad               9   
21318   19            Private   138153   Some-college              10   
21490   19            Private   146679   Some-college              10   
21875   49            Private    31267        7th-8th               4   
22300   25            Private   195994        1st-4th               2   
22367   44            Private   367749      Bachelors              13   
22494   49   Self-emp-not-inc    43479   Some-college              10   
25872   23            Private   240137        5th-6th               3   
26313   28            Private   274679        Masters              14   
28230   27            Private   255582        HS-grad               9   
28522   42            Private   204235   Some-college              10   
28846   39            Private    30916        HS-grad               9   
29157   38            Private   207202        HS-grad               9   
30845   46            Private   133616   Some-college              10   
31993   19            Private   251579   Some-college              10   
32404   35            Private   379959        HS-grad               9   

            marital-status          occupation    relationship  \
4881         Never-married        Craft-repair   Not-in-family   
5104         Never-married       Other-service   Not-in-family   
9171         Never-married      Prof-specialty       Own-child   
11631        Never-married        Tech-support   Not-in-family   
13084        Never-married     Priv-house-serv   Not-in-family   
15059        Never-married     Farming-fishing   Not-in-family   
17040   Married-civ-spouse        Craft-repair         Husband   
18555        Never-married       Other-service   Not-in-family   
18698        Never-married     Farming-fishing   Not-in-family   
21318        Never-married        Adm-clerical       Own-child   
21490        Never-married     Exec-managerial       Own-child   
21875   Married-civ-spouse        Craft-repair         Husband   
22300        Never-married     Priv-house-serv   Not-in-family   
22367        Never-married      Prof-specialty   Not-in-family   
22494   Married-civ-spouse        Craft-repair         Husband   
25872        Never-married   Handlers-cleaners   Not-in-family   
26313        Never-married      Prof-specialty   Not-in-family   
28230        Never-married   Machine-op-inspct   Not-in-family   
28522   Married-civ-spouse      Prof-specialty         Husband   
28846   Married-civ-spouse        Craft-repair         Husband   
29157   Married-civ-spouse   Machine-op-inspct         Husband   
30845             Divorced        Adm-clerical       Unmarried   
31993        Never-married       Other-service       Own-child   
32404             Divorced       Other-service   Not-in-family   

                      race      sex   capital-gain   capital-loss  \
4881                 White     Male              0              0   
5104    Asian-Pac-Islander     Male              0              0   
9171                 White   Female              0              0   
11631                White   Female              0              0   
13084                White   Female              0              0   
15059                White     Male              0              0   
17040                White     Male            

In [90]:
df.drop_duplicates(inplace=True)

print("Data Duplikat: ")
df[df.duplicated()]

Data Duplikat: 


Empty DataFrame
Columns: [age,  workclass,  fnlwgt,  education,  education-num,  marital-status,  occupation,  relationship,  race,  sex,  capital-gain,  capital-loss,  hours-per-week,  native-country,  income, fnlwgt]
Index: []

## OneHot Encoding

In [91]:
encoder = OneHotEncoder(sparse=False)
sexEnc = encoder.fit_transform(df[[" sex"]])

In [92]:
sex = pd.DataFrame(sexEnc)
df = df.join(sex)

df = df.rename(columns={
    0 : 'Female',
    1 : 'Male'
})

In [93]:
df.head()

age          workclass   fnlwgt   education   education-num  \
0   39          State-gov    77516   Bachelors              13   
1   50   Self-emp-not-inc    83311   Bachelors              13   
2   38            Private   215646     HS-grad               9   
3   53            Private   234721        11th               7   
4   28            Private   338409   Bachelors              13   

        marital-status          occupation    relationship    race      sex  \
0        Never-married        Adm-clerical   Not-in-family   White     Male   
1   Married-civ-spouse     Exec-managerial         Husband   White     Male   
2             Divorced   Handlers-cleaners   Not-in-family   White     Male   
3   Married-civ-spouse   Handlers-cleaners         Husband   Black     Male   
4   Married-civ-spouse      Prof-specialty            Wife   Black   Female   

    capital-gain   capital-loss   hours-per-week  native-country  income  \
0           2174              0               40   United-States   <=50K   
1              0              0               13   United-States   <=50K   
2              0              0               40   United-States   <=50K   
3              0              0               40   United-States   <=50K   
4              0              0               40            Cuba   <=50K   

   fnlwgt  Female  Male  
0   77516     0.0   1.0  
1   83311     0.0   1.0  
2  215646     0.0   1.0  
3  234721     0.0   1.0  
4  338409     1.0   0.0