# Posttest_7
Nama  : Hendi
NIM   : 2009106009
Kelas : Praktikum Kecerdasn Buatan A1 2020

## Import Library

In [29]:
import tensorflow as tf

## Random

In [30]:
random_tensor = tf.random.normal([5,5],mean=0,stddev=1,seed=1)

random_tensor.numpy()

array([[-0.32386488,  0.99133694,  0.14024267,  1.2573972 ,  0.09992335],
       [ 0.18983224, -0.28711194, -1.7413595 ,  1.8718754 , -2.0104504 ],
       [-1.4673029 , -1.2721989 , -0.7803738 ,  0.94073033, -0.06164822],
       [-2.0842526 ,  0.61423135, -1.451092  , -0.88693523, -0.96740866],
       [ 0.94831836, -0.6974499 ,  0.5391437 , -0.52970064, -2.0105364 ]],
      dtype=float32)

## Prima

In [31]:
prima = [[2,3,5,7,11],[13,17,19,23,29],[31,37,41,43,47],[53,59,61,67,71],[73,79,83,89,97]]

prime_tensor = tf.convert_to_tensor(prima, dtype=tf.float32)

prime_tensor.numpy()

array([[ 2.,  3.,  5.,  7., 11.],
       [13., 17., 19., 23., 29.],
       [31., 37., 41., 43., 47.],
       [53., 59., 61., 67., 71.],
       [73., 79., 83., 89., 97.]], dtype=float32)

## Dimensi Tensor

In [32]:
random_tensor.get_shape()
random_tensor.shape

TensorShape([5, 5])

In [33]:
tf.shape(prime_tensor).numpy()
prime_tensor.shape

TensorShape([5, 5])

## Artimatika

### Tambah

In [34]:
print(tf.add(random_tensor, prime_tensor))

tf.Tensor(
[[ 1.6761351  3.9913368  5.1402426  8.257397  11.099923 ]
 [13.189833  16.712889  17.25864   24.871876  26.98955  ]
 [29.532698  35.727802  40.219627  43.94073   46.93835  ]
 [50.91575   59.61423   59.54891   66.11307   70.03259  ]
 [73.94832   78.30255   83.53915   88.4703    94.98946  ]], shape=(5, 5), dtype=float32)


### Kurang

In [35]:
print(tf.subtract(random_tensor, prime_tensor))

tf.Tensor(
[[ -2.323865   -2.0086632  -4.8597574  -5.742603  -10.900077 ]
 [-12.810167  -17.287111  -20.74136   -21.128124  -31.01045  ]
 [-32.467304  -38.272198  -41.780373  -42.05927   -47.06165  ]
 [-55.08425   -58.38577   -62.45109   -67.88693   -71.96741  ]
 [-72.05168   -79.69745   -82.46085   -89.5297    -99.01054  ]], shape=(5, 5), dtype=float32)


### Kali

In [36]:
print(tf.divide(random_tensor, prime_tensor))

tf.Tensor(
[[-0.16193244  0.33044565  0.02804853  0.17962816  0.00908394]
 [ 0.01460248 -0.01688894 -0.0916505   0.08138589 -0.06932587]
 [-0.04733235 -0.03438376 -0.01903351  0.02187745 -0.00131166]
 [-0.03932552  0.0104107  -0.02378839 -0.01323784 -0.01362547]
 [ 0.01299066 -0.00882848  0.00649571 -0.00595169 -0.02072718]], shape=(5, 5), dtype=float32)


### Log

In [37]:
print(tf.math.log(random_tensor, prime_tensor))

tf.Tensor(
[[        nan -0.0087008  -1.964381    0.22904386 -2.3033519 ]
 [-1.6616145          nan         nan  0.62694085         nan]
 [        nan         nan         nan -0.06109876         nan]
 [        nan -0.48738366         nan         nan         nan]
 [-0.05306501         nan -0.6177732          nan         nan]], shape=(5, 5), dtype=float32)


### Pangkat

In [38]:
print(tf.pow(random_tensor, prime_tensor))

tf.Tensor(
[[ 1.0488846e-01  9.7423530e-01  5.4250133e-05  4.9694390e+00
   9.9160073e-12]
 [ 4.1572837e-10 -6.1216887e-10 -3.7746809e+04  1.8296565e+06
  -6.2446387e+08]
 [-1.4524903e+05 -7.3881514e+03 -3.8406979e-05  7.2277203e-02
  -0.0000000e+00]
 [-8.0235882e+16  3.2477805e-13 -7.3011604e+09 -3.2266942e-04
  -9.5127881e-02]
 [ 2.0780388e-02 -4.3403966e-13  5.3885902e-23 -2.7460855e-25
  -2.6379033e+29]], shape=(5, 5), dtype=float32)


## Nilai Maksimum

In [39]:
print(tf.sort(random_tensor, direction='DESCENDING'))

tf.Tensor(
[[ 1.2573972   0.99133694  0.14024267  0.09992335 -0.32386488]
 [ 1.8718754   0.18983224 -0.28711194 -1.7413595  -2.0104504 ]
 [ 0.94073033 -0.06164822 -0.7803738  -1.2721989  -1.4673029 ]
 [ 0.61423135 -0.88693523 -0.96740866 -1.451092   -2.0842526 ]
 [ 0.94831836  0.5391437  -0.52970064 -0.6974499  -2.0105364 ]], shape=(5, 5), dtype=float32)


In [40]:
print(tf.argsort(random_tensor, direction='DESCENDING'))

tf.Tensor(
[[3 1 2 4 0]
 [3 0 1 2 4]
 [3 4 2 1 0]
 [1 3 4 2 0]
 [0 2 3 1 4]], shape=(5, 5), dtype=int32)


## Nilai Minimum

In [41]:
print(tf.sort(random_tensor, direction='DESCENDING'))

tf.Tensor(
[[ 1.2573972   0.99133694  0.14024267  0.09992335 -0.32386488]
 [ 1.8718754   0.18983224 -0.28711194 -1.7413595  -2.0104504 ]
 [ 0.94073033 -0.06164822 -0.7803738  -1.2721989  -1.4673029 ]
 [ 0.61423135 -0.88693523 -0.96740866 -1.451092   -2.0842526 ]
 [ 0.94831836  0.5391437  -0.52970064 -0.6974499  -2.0105364 ]], shape=(5, 5), dtype=float32)


In [42]:
print(tf.argsort(random_tensor, direction='DESCENDING'))

tf.Tensor(
[[3 1 2 4 0]
 [3 0 1 2 4]
 [3 4 2 1 0]
 [1 3 4 2 0]
 [0 2 3 1 4]], shape=(5, 5), dtype=int32)


## Concatenation

In [43]:
print(f"Sebelum : {random_tensor.shape} {prime_tensor.shape}")

Sebelum : (5, 5) (5, 5)


In [44]:
concat_sample = tf.concat([random_tensor, prime_tensor], axis=0)
print(f"Sesudah : {concat_sample.shape}")

Sesudah : (10, 5)


## Urutkan

In [45]:
print(tf.sort(random_tensor, direction="DESCENDING"))

tf.Tensor(
[[ 1.2573972   0.99133694  0.14024267  0.09992335 -0.32386488]
 [ 1.8718754   0.18983224 -0.28711194 -1.7413595  -2.0104504 ]
 [ 0.94073033 -0.06164822 -0.7803738  -1.2721989  -1.4673029 ]
 [ 0.61423135 -0.88693523 -0.96740866 -1.451092   -2.0842526 ]
 [ 0.94831836  0.5391437  -0.52970064 -0.6974499  -2.0105364 ]], shape=(5, 5), dtype=float32)


In [46]:
print(tf.sort(prime_tensor, direction="DESCENDING"))

tf.Tensor(
[[11.  7.  5.  3.  2.]
 [29. 23. 19. 17. 13.]
 [47. 43. 41. 37. 31.]
 [71. 67. 61. 59. 53.]
 [97. 89. 83. 79. 73.]], shape=(5, 5), dtype=float32)
