# Posttest_7
Nama  : Hendi
NIM   : 2009106009
Kelas : Praktikum Kecerdasn Buatan A1 2020

## Klasifikasi Dataset Iris sklearn

## Import Library

In [22]:
import numpy as np
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import OneHotEncoder
from keras.layers import Dense
from keras.optimizers import Adam
from keras.models import Sequential

## PreProcessing

In [23]:
df = load_iris()

In [24]:
print('Example data: ')
print(df.data[:5])

Example data: 
[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]]


In [25]:
print('Example labels: ')
print(df.target[:5])

Example labels: 
[0 0 0 0 0]


### Reshape

In [26]:
x = df.data
yx = df.target.reshape(-1, 1)

### One Hot Encode

In [27]:
encoder = OneHotEncoder(sparse=False)
y = encoder.fit_transform(yx)

### Splitdata

In [28]:
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.3)

## Modelling

### Sequential

In [29]:
model = Sequential()

model.add(Dense(10, input_shape=(4,), activation='relu', name='var1'))
model.add(Dense(10, activation='relu', name='var2'))
model.add(Dense(3, activation='softmax', name='output'))

### Compile

In [30]:
optimizer = Adam(lr=0.001)
model.compile(optimizer, loss='categorical_crossentropy', metrics=['accuracy'])

C:\Users\ROG\PycharmProjects\A1-20\Hendi-009\lib\site-packages\keras\optimizers\optimizer_v2\adam.py:114: UserWarning: The `lr` argument is deprecated, use `learning_rate` instead.
  super().__init__(name, **kwargs)


In [31]:
print('Summary: ')
print(model.summary())

Summary: 
Model: "sequential_1"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 var1 (Dense)                (None, 10)                50        
                                                                 
 var2 (Dense)                (None, 10)                110       
                                                                 
 output (Dense)              (None, 3)                 33        
                                                                 
Total params: 193
Trainable params: 193
Non-trainable params: 0
_________________________________________________________________
None


## Training

In [32]:
history = model.fit(x_train, y_train, verbose=2, steps_per_epoch=10, epochs=20, validation_data=(x, y))

Epoch 1/20
10/10 - 1s - loss: 1.0444 - accuracy: 0.3333 - val_loss: 1.0165 - val_accuracy: 0.3533 - 921ms/epoch - 92ms/step
Epoch 2/20
10/10 - 0s - loss: 0.9968 - accuracy: 0.4857 - val_loss: 0.9792 - val_accuracy: 0.6133 - 65ms/epoch - 6ms/step
Epoch 3/20
10/10 - 0s - loss: 0.9609 - accuracy: 0.7524 - val_loss: 0.9450 - val_accuracy: 0.8333 - 64ms/epoch - 6ms/step
Epoch 4/20
10/10 - 0s - loss: 0.9283 - accuracy: 0.8476 - val_loss: 0.9109 - val_accuracy: 0.8133 - 72ms/epoch - 7ms/step
Epoch 5/20
10/10 - 0s - loss: 0.8930 - accuracy: 0.8286 - val_loss: 0.8741 - val_accuracy: 0.7533 - 64ms/epoch - 6ms/step
Epoch 6/20
10/10 - 0s - loss: 0.8539 - accuracy: 0.7714 - val_loss: 0.8316 - val_accuracy: 0.7800 - 65ms/epoch - 6ms/step
Epoch 7/20
10/10 - 0s - loss: 0.8122 - accuracy: 0.7905 - val_loss: 0.7926 - val_accuracy: 0.7800 - 56ms/epoch - 6ms/step
Epoch 8/20
10/10 - 0s - loss: 0.7761 - accuracy: 0.7714 - val_loss: 0.7579 - val_accuracy: 0.7800 - 64ms/epoch - 6ms/step
Epoch 9/20
10/10 - 0s 

In [33]:
print("Akurasi validasi :", history.history["val_accuracy"][-1])

Akurasi validasi : 0.95333331823349


## Evaluasi

In [34]:
result = model.evaluate(x_test, y_test)
print('Hasil Tes Loss: {:4f}'.format(result[0]))
print('Hasil Tes Akurasi : {:4f}'.format(result[1]))

2/2 [==============================] - 0s 0s/step - loss: 0.4603 - accuracy: 0.9111
Hasil Tes Loss: 0.460297
Hasil Tes Akurasi : 0.911111
